# Changes here will be overwritten by Copier
_commit: 5c63cb2
_src_path: https://github.com/python-project-templates/base.git
add_extension: js
email: t.paine154@gmail.com
github: airflow-laminar
project_description: Utilities for load balancing DAGs
project_name: airflow balancer
python_version_primary: '3.11'
team: the airflow-balancer authors
