name: Docs
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-ext/python/setup@main
        with:
          version: 3.11
      - uses: actions-ext/node/setup@main
      - run: pip install .
      - run: pip install yardang
      - run: yardang build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html
